Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class RazorController : Controller
    {
        public IActionResult Snacks()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<body>

    <main>

        @for(int i=1;i < 6; i++)
        {
            <div class="card mb-3" style="max-width: 540px;">
         <div class="row g-0">
        <div class="col-md-4">
           
                        <img src="https://img.pizza/300/300" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                            <h5 class="card-title">Pizza margherita @i</h5>
                <p class="card-text"></p>
                            <p class="card-title"><strong>    @{
                                        int randomNumber = new Random().Next(6, 16);
                                    } @randomNumber,00 €</strong></p>
                <p class="card-text"></p>
                <p class="card-text"><small class="text-muted">tipica pizza napoletana, condita con pomodoro, mozzarella, basilico fresco, sale e olio</small></p>
            </div>
        </div>
    </div></div>
        

 }
        

    
      
</main>

</body>

Views/Razor/Snacks.cshtml
@{
    Layout = "_LayoutSnacks";
}

<a class="btn btn-primary btn-lg" asp-area="" asp-controller="Home" asp-action="Index">Torna alla pagina principale</a>
<h1>Razor Snacks</h1>


@*1. Dichiarare una variabile valorizzandola con il nostro nome.
Dichiarare un'altra variabile valorizzandola con il nostro cognome.
Stampare il nostro nome e cognome all'interno di un tag h2.*@


@{
    var nome = "Gianmarco";
    var cognome = "Ruffi";
}

<h2>1. <span>Nome: @nome - Cognome: @cognome</span></h2>

@*2. Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
Stampare dentro uno span il risultato.*@

@{
    int i, sum = 0, n;
    n = 8;
    for (i = 1; i <= n; i++)
    {
        sum = sum + i;
    }

}
<span>2. La somma dei numeri che vanno da 1 a @n è: @sum</span>
<br />

@*3. Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina*@

@{
    string str = "Nel mezzo del cammin di nostra vita";
        char ch = 'a';

        int freq = 0;
        foreach (char c in str)
        {
            if (c == ch) {
                freq++;
            }
        }
        }
<span>3. La lettera "a" è presente il seguente numero di volte: @freq</span>
<br />


@*4. Creare una List<int>
    di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70*@

@{

List<int> randomNumbers = new List<int>();
        for(int j = 0; j<20; j++){
    Random rand = new Random();
        randomNumbers.Add(rand.Next(1,91));
        }
}
4. <span>Lista di numeri random compresi tra 20 e 70</span>
<ul>
    @foreach (int num in randomNumbers)
    {
        if (Enumerable.Range(20, 70).Contains(num))
        {
        <li>@num</li>
        }
    }
    </ul>


@*    5. Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi*@

@{
    DateTime now = DateTime.Now;
}

5. <span><strong>Data attuale: @now.Year/@now.Month/@now.Day</strong> <br>
    <strong>Ora attuale: @now.Hour: @now.Minute: @now.Second</strong></span>
<br>

@*    6. Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina*@

@*    a. la data di 7 giorni fa
    b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
    c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)*@

@{
    DateTime today = DateTime.Now;
    DateTime dt7 = today.AddDays(-7);
    DateTime dt1 = today.AddYears(1);

}

6. <span><strong>a. Data di 7 giorni fa: @dt7</strong> </span><br>
<span><strong>b. Oggi è: @today.DayOfWeek</strong> </span>
<br>
<span><strong>c. Tra un anno sarà: @dt1.DayOfWeek</strong> </span>
<br>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pizze</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li> <a class="navbar-brand" asp-area="" asp-controller="Razor" asp-action="Snacks">Vai agli Snack</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutSnacks.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Snacks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>

<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>